version: '3'

services:

  traccar:
    image: traccar/traccar:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '80:8082'
      - '5000-5150:5000-5150'
      - '5000-5150:5000-5150/udp'
    volumes:
      - ./data/logs:/opt/traccar/logs:rw
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro

  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: mysqlUser
      MYSQL_PASSWORD: mySecretPassword
      MYSQL_DATABASE: traccar
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - traccar-mysql-volume:/var/lib/mysql
volumes:
  traccar-mysql-volume:
